---
# file: roles/cdh_hbase_config/tasks/main.yml

- name: copy /etc/hbase/conf.empty to /etc/hbase/conf.{{ site_name|lower }}
  command: creates=/etc/hbase/conf.{{ site_name|lower }} cp -R -p /etc/hbase/conf.dist /etc/hbase/conf.{{ site_name|lower }}
  tags: hbase

- name: configure HBase in /etc/hbase/conf.{{ site_name|lower }}
  template: src={{ item }} dest=/etc/hbase/conf.{{ site_name|lower }}/{{ item }} owner=root group=root mode=0644
  with_items:
    - hbase-env.sh
    - hbase-site.xml
    - regionservers
  notify:
    - restart hbase-master
    - restart hbase-regionserver
  tags:
    - hbase
    - configuration

- name: run 'update-alternatives' to install HBase configuration
  command: update-alternatives --install /etc/hbase/conf hbase-conf /etc/hbase/conf.{{ site_name|lower }} 50
  tags: hbase

- name: run 'update-alternatives' to set HBase configuration
  command: update-alternatives --set hbase-conf /etc/hbase/conf.{{ site_name|lower }}
  tags: hbase