---
# file: roles/elasticsearch_curator/tasks/main.yml

- name: install python-pip via apt
  apt: pkg=python-pip
  tags: elasticsearch_curator

- name: install elasticsearch-curator via pip
  command: pip install --upgrade https://github.com/elasticsearch/curator/tarball/master
  tags: elasticsearch_curator

- name: install the elasticsearch-curator crontab at /etc/cron.d/elasticsearch-curator
  template: src=elasticsearch-curator.cron.d dest=/etc/cron.d/elasticsearch-curator owner=root group=root mode=644
  tags: elasticsearch_curator