---
# file: roles/cdh_hive_mysql_metastore/tasks/main.yml

- name: create MySQL db 'metastore'
  mysql_db: name=metastore state=present
            login_user=root login_password=hive_{{ site_name }}
  tags:
    - mysql
    - hive

- name: init Hive metastore schema
  shell: mysql -uroot -phive_{{ site_name }} metastore < /usr/lib/hive/scripts/metastore/upgrade/mysql/hive-schema-0.10.0.mysql.sql
  tags:
    - mysql
    - hive

- name: add and grant MySQL user 'hiveuser'
  mysql_user: name=hiveuser host=localhost password=hive_{{ site_name }} priv=metastore.*:ALL state=present
              login_user=root login_password=hive_{{ site_name }}
  tags:
    - mysql
    - hive